# Default property values

# ALL
DEFAULT_DESCRIPTION = ''
DEFAULT_SUBTYPE = 'NONE'

# FLOAT
DEFAULT_MIN_FLOAT = 0.0
DEFAULT_MAX_FLOAT = 1.0
DEFAULT_SOFT_MIN_FLOAT = 0.0
DEFAULT_SOFT_MAX_FLOAT = 1.0
DEFAULT_STEP_FLOAT = 0.01
DEFAULT_PRECISION_FLOAT = 3

# FLOAT ARRAY
DEFAULT_FLOAT_ARRAY = [0.0, 0.0, 0.0]
DEFAULT_MIN_FLOAT_ARRAY = 0.0
DEFAULT_MAX_FLOAT_ARRAY = 1.0
DEFAULT_SOFT_MIN_FLOAT_ARRAY = 0.0
DEFAULT_SOFT_MAX_FLOAT_ARRAY = 1.0
DEFAULT_STEP_FLOAT_ARRAY = 0.01
DEFAULT_PRECISION_FLOAT_ARRAY = 3

# INT
DEFAULT_MIN_INT = 0
DEFAULT_MAX_INT = 1
DEFAULT_SOFT_MIN_INT = 0
DEFAULT_SOFT_MAX_INT = 1
DEFAULT_STEP_INT = 1

# INT ARRAY
DEFAULT_INT_ARRAY = [0, 0, 0]
DEFAULT_MIN_INT_ARRAY = 0
DEFAULT_MAX_INT_ARRAY = 1
DEFAULT_SOFT_MIN_INT_ARRAY = 0
DEFAULT_SOFT_MAX_INT_ARRAY = 1
DEFAULT_STEP_INT_ARRAY = 1

# BOOL
DEFAULT_VALUE_BOOL = False
DEFAULT_BOOL_ARRAY = [False, False, False]

# BOOL ARRAY
DEFAULT_VALUE_BOOL_ARRAY = False