name: Dummy Status Check

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Report success
        run: echo "This check always passes."
